using OutSystems.ExternalLibraries.SDK;

namespace Without.Systems.SecurityToken.Structures;

[OSStructure(Description = "Contains information about the provided context")]
public struct ProvidedContext
{
    [OSStructureField(
        Description = "The signed and encrypted trusted context assertion generated by the context provider.",
        DataType = OSDataType.Text,
        IsMandatory = false)]
    public string ContextAssertion;
    
    [OSStructureField(Description = "The context provider ARN from which the trusted context assertion was generated.",
        DataType = OSDataType.Text,
        IsMandatory = false)]
    public string ProviderArn;
    
}